FROM ubuntu:18.04

MAINTAINER Frojd
LABEL version="v1.0.0"

ENV TZ=Europe/Stockholm
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# apt-get install All the things!

RUN apt-get update && apt-get -y install nodejs npm vim curl \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && mkdir -p /app

EXPOSE 1234

# Default command for machine
# CMD cd /app/frontend; npm run dev:server
